### ISSUE TITLE
Missing ESLint configuration in vanilla install of pro package

### ISSUE THREAD

**Issue by haasted** [creativetimofficial/ct-vue-material-dashboard-pro#1]
I'm having trouble getting things up and running when following the instructions at https://www.creative-tim.com/product/vue-material-dashboard-pro.

# Current Behavior

`yarn serve` (and also `npm run dev`) complains of a missing ESLint configuration.

```
$ yarn serve
yarn run v1.6.0
$ vue-cli-service serve --open
 INFO  Starting development server...
 94% after seal

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                     10:15:34 AM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy ([Project-path]/node_modules/eslint/lib/config.js:255:39)
    at Config.getConfigHierarchy ([Project-path]/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector ([Project-path]/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig ([Project-path]/node_modules/eslint/lib/config.js:329:29)
    at processText ([Project-path]/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText ([Project-path]/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint ([Project-path]/node_modules/eslint-loader/index.js:229:17)
    at transform ([Project-path]/node_modules/eslint-loader/index.js:212:18)
    at [Project-path]/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback ([Project-path]/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

```
## Steps to Reproduce

1. Download the Pro package and unzip it.
2. Run `npm install`
3. Run `npm run dev`

Using the equivalent yarn commands seems to lead to the same results.

## Context
```
$ node --version && yarn --version && npm --version && vue -V
v9.11.1
1.6.0
5.6.0
3.0.0-rc.5
```
Mac os x v10.11.6

**Comment by haasted** [comment]
Never mind. My mistake. I moved all the files to another directory and forgot to include the hidden configuration files. Apologies.

**Comment by dragosct10** [comment]
Hi, @haasted! Thank you for using our product. I just wanted to send you the message to tell you that is very weird because on our side everything is working fine and now I edited the message:D. I'm glad that all the things are good now. 

Regards, 
Dragos

**Comment by Thyiad** [comment]
Thank you, I have zhe same problem at now.
