### ISSUE TITLE
[Bug] eslint dependency error

### ISSUE THREAD

**Issue by gopeca** [creativetimofficial/ct-vue-material-dashboard-pro#118]
### Version
latest
### Reproduction link
http://localhost
### Operating System
Ubuntu
### Device
pc
### Browser & Version
npm
### Steps to reproduce
sudo npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-material-dashboard-pro@1.5.0
npm ERR! Found: eslint@7.30.0
npm ERR! node_modules/eslint
npm ERR! dev eslint@"7.30.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR! dev @vue/cli-plugin-eslint@"4.5.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-08-18T10_48_02_836Z-debug.log
### What is expected?
Get dependency tree
### What is actually happening?
error

---

**Comment by dy20c** [comment]
i got this template 30minutes ago. also have same problem.
Do i fix it by myself?
+. when i change eslint version 6.8.0, then i got a conflict error node-sass&sass-loader versions.

**Comment by dragosct10** [comment]
Hi, @dy20c & @gopeca! Thanks for using our products. Please be sure that you have the latest npm and nodejs installed. The product is working fine, we've just tested. 

Regards,
Dragos

**Comment by dy20c** [comment]
> Hi, @dy20c & @gopeca! Thanks for using our products. Please be sure that you have the latest npm and nodejs installed. The product is working fine, we've just tested.
> 
> Regards,
> Dragos

Hi, @dragosct10 
Thanks for the fast reply.


The latest premium (v1.5.0) version not worked on my macOS(BigSur).
Finally, I can work on it through these downgrade.

node = 16.10.0 ->  node v14.17.6
npm = v7.24.0 -> v6.14.15
--package.json devDependencies--

1. error: eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
my action : eslint 7.30.0 -> 6.8.0 

2. error: 
node-sass@"6.0.1" 
peerOptional node-sass@"^4.0.0" from sass-loader@8.0.2 
Conflicting peer dependency: node-sass@4.14.1

my action : delete "node-sass": "6.0.1" on dev dependencies

----another issue------
"fibers": "5.0.0" not supported on nodejs v16.x or higher.
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.

How can i work it on the latest npm and node version?

Thank you.

Regards,
@dy20c

**Comment by tgshore97** [comment]
I also have this eslint dependency issue

_Versions_
Node: 17.1.0
npm: 8.1.3
nvm: 0.33.0

Many deprecated packages warnings
1. Same error as @dy20c, I also changed eslint from 7.3.0 -> 6.8.0 in package.json

Packages all install, though with 46 vulnerabilities (22 moderate, 24 high)

When attempting to run the development server, I get errors: "digital envelope routines unsupported"

`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/tavis/Desktop/app/vue-material-dashboard-pro-v1.5.0/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
`

**Comment by dragosct10** [comment]
Hi, @tgshore97! Thanks for using our products. You are using the latest npm and node but not the latest LTS nodejs version and this cause an issue for you. Please try with an LTS version. 

Regards,
Dragos

**Comment by tgshore97** [comment]
Hi @dragosct10, this has not solved the issue. I have a clean instal of Linux so there should be minimal library conflicts. 
Using these versions of the stated requirements:
node.js: 17.1.0 (through NVM)
npm: 8.1.3

Error message that I'm getting
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-material-dashboard-pro@1.5.0
npm ERR! Found: eslint@7.30.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.30.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.13" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/tavis/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tavis/.npm/_logs/2021-11-10T12_53_08_566Z-debug.log
```

Doing the same with node-sass, altering it to version 4.14.1
The final error that I can't seem to get beyond is:

```
npm ERR! code 127
npm ERR! path /home/tavis/Desktop/application/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/tavis/Desktop/application/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/tavis/Desktop/application/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/tavis/Desktop/application/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/tavis/Desktop/application/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/tavis/Desktop/application/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/tavis/Desktop/application/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/tavis/Desktop/application/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 5.11.0-40-generic
npm ERR! gyp ERR! command "/home/tavis/.nvm/versions/node/v17.1.0/bin/node" "/home/tavis/Desktop/application/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /home/tavis/Desktop/application/node_modules/fibers
npm ERR! gyp ERR! node -v v17.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: 1: nodejs: not found


```

**Comment by dragosct10** [comment]
Hi, guys! I've tested and the product is working with the following changes. 

1. First you must have the latest LTS version of nodejs which is `16.13.0` and this version comes with the latest npm `8.1.3`.
2. Go to the `package.json` file and remove `"fibers": "5.0.0"`, `"node-sass": "6.0.1"` and put the version of the dependence named `"eslint"` version `6.8.0`.
3. Remove the `node_modules`, `package-lock.json` and run `npm install`. 

Now remove the product should work fine. 

Regards,
Dragos

**Comment by tgshore97** [comment]
Thanks,

This enabled npm install to complete successfully.
However, when I run ``` npm run dev ```, The error shown below is displayed. With some quick googling, it's suggested that this could be related to how SSL 3.0 is more restrictive.

```

 INFO  Starting development server...
10% building 2/2 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/tavis/Desktop/application/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/tavis/Desktop/application/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/tavis/Desktop/application/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active /home/tavis/Desktop/application/node_modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/tavis/Desktop/application/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tavis/Desktop/application/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/tavis/Desktop/application/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/tavis/Desktop/application/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/tavis/Desktop/application/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/tavis/Desktop/application/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Comment by dragosct10** [comment]
Yes, this is a strange error! I hope that will come updates for this in the near future. Please try one of the options from [here](https://stackoverflow.com/questions/69692842/error0308010cdigital-envelope-routinesunsupported).

**Comment by tgshore97** [comment]
@dragosct10 Amazing thank you, executing ```export NODE_OPTIONS=--openssl-legacy-provider``` and rerunning the build sorted this error!

Have a nice day!

**Comment by yoandysse** [comment]
For those who have the error
![image](https://user-images.githubusercontent.com/15040570/187043934-935e1f1e-e445-4a9c-9355-3c20d41fd90a.png)


try:
`npm install --save --legacy-peer-deps `

**Comment by sajadevo** [comment]
Hey everyone, 

This issue is fixed on the latest version of the product.

Cheers,
Sajad
